# Tipo de alteração
tipo:
  feat: "✨ feat: Nova funcionalidade"
  fix: "🐛 fix: Correção de bug"
  docs: "📝 docs: Documentação"
  style: "💄 style: Formatação de código"
  refactor: "♻️ refactor: Refatoração de código"
  perf: "⚡ perf: Melhorias de performance"
  test: "✅ test: Testes"
  build: "👷 build: Sistema de build"
  ci: "🔧 ci: Integração contínua"
  chore: "🔨 chore: Tarefa de manutenção"
  revert: "⏪ revert: Reverter commit"

# Escopo (opcional)
escopo: |
  Qual o escopo da alteração? (opcional)

# Descrição curta
mensagem: |
  Descrição curta da alteração:

# Corpo (opcional)
corpo: |
  Descrição mais detalhada da alteração (opcional):

# Quebras de compatibilidade (opcional)
quebras: |
  Lista de quebras de compatibilidade (opcional):

# Issues fechadas (opcional)
issues: |
  Lista de issues fechadas por esta alteração (opcional):
